### ISSUE TITLE
Teleportation Samples (via Binder/Notebook) is broken

### ISSUE THREAD

**Issue by cleemullins** [MicrosoftDocs/quantum-docs-pr#483] opened 2019-08-13 05:00 UTC
Running the samples results in a Dependency Issue / failure. 

I can't cut/paste unfortunately, but the issue with with Powershell and SSL dependencies. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Getting Started with the Microsoft Quantum Development Kit](https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @anpaz-msft
* Microsoft Alias: **andres.paz@microsoft.com**

**Comment by cgranade** [comment] 2019-08-13 21:06
Thanks for the report! Looks like we're already tracking this on microsoft/quantum, though, so I'm closing as a duplicate of microsoft/quantum#220.

**Closed by cgranade** 2019-08-13 21:06 UTC
