### ISSUE TITLE
iqsharp could not be installed

### ISSUE THREAD

**Issue by kaiiyer** [MicrosoftDocs/quantum-docs-pr#629] opened 2019-12-02 11:04 UTC
# Issue Title
iqsharp could not be installed

# General

.NET Core 3.0
---------------------
SDK Version: 3.0.101
---------------------
OS (Version): Parrot GNU/LINUX Release 3.11 (64-bit)

Tool 'microsoft.quantum.iqsharp' is already installed and when i try using the command "dotnet iqsharp install", I get the following error.

Could not execute because the specified command or file was not found.

![Screenshot at 2019-12-02 16-32-04](https://user-images.githubusercontent.com/24914913/69954256-e0a0e900-1520-11ea-9cc7-006e26abee0a.png)

**Comment by cgranade** [comment] 2019-12-03 17:39
Thanks for the report, @kaiiyer! This looks like a duplicate of the issue reported as microsoft/iqsharp#68, so I'm closing this issue, but please feel free to reopen if that's not the case. Thank you!

**Closed by cgranade** 2019-12-03 17:39 UTC
