### ISSUE TITLE
python code cannot find the namespace declared in qsharp code

### ISSUE THREAD

**Issue by zhizeng8** [MicrosoftDocs/quantum-docs-pr#925] opened 2020-06-23 09:53 UTC
I'm a new comer. I failed to run the hello world with python. 
from HelloWorld import SayHello
ModuleNotFoundError: No module named 'HelloWorld'
It seems the python code cannot find the namespace declared in qsharp code.
I am using vs code, how can I fix it? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/qrng?tabs=tabid-qsharp)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by geduardo** [comment] 2020-06-23 13:53
Hi @zhizeng8, did you install the QDK for Python?

Installation link: https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall

**Comment by zhizeng8** [comment] 2020-06-23 14:23
> Hi @zhizeng8, did you install the QDK for Python?
> 
> Installation link: https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall

I have installed QDK, is (QDK) different from (QDK for python)? Thank you! @geduardo

**Comment by zhizeng8** [comment] 2020-06-23 14:44
I can run Q# command line applications successfully and import qsharp in .py successfully. The only problem is from HelloWorld import SayHello. Thank you! @geduardo

**Comment by rmshaffer** [comment] 2020-06-23 16:08
@zhizeng8, your .qs file must be in the same folder as the .py file. If that still doesn't work, can you share the contents your .qs file?

**Comment by zhizeng8** [comment] 2020-06-23 16:14
namespace HelloWorld {
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Canon;

    operation SayHello() : Unit {
        Message("Hello from quantum world!");
    }
}

**Comment by rmshaffer** [comment] 2020-06-23 16:24
Can you confirm that the .py and .qs files are located in the same folder? Can you copy/paste the output you get when running python?

You can also try running `python -c "import qsharp; qsharp.reload()"` from the folder with your .py and .qs files, if you have recently upgraded to a new version.

Also, so we know what versions you have installed, can you run `pip show qsharp` and `dotnet iqsharp --version` and report the output?

**Comment by zhizeng8** [comment] 2020-06-23 16:29
.py and .qs files are located in the same folder.

Traceback (most recent call last):
  File "/Users/zengzhi/VscodeProjects/HelloQuantum/hello_world.py", line 3, in <module>
    from HelloWorld import SayHello
ModuleNotFoundError: No module named 'HelloWorld'

Name: qsharp
Version: 0.11.2006.403
Summary: Python client for Q#, a domain-specific quantum programming language
Home-page: https://github.com/microsoft/iqsharp
Author: Microsoft
Author-email: None
License: UNKNOWN
Location: /Library/anaconda3/lib/python3.7/site-packages
Requires: jupyter-client
Required-by: qdk

iqsharp: 0.11.2006.403
Jupyter Core: 1.3.60623.0
.NET Runtime: .NETCoreApp,Version=v3.1

**Comment by rmshaffer** [comment] 2020-06-23 16:33
Can you ensure that the .qs file is saved? Try closing and re-opening it from the same folder to ensure that it has the correct contents?

**Comment by zhizeng8** [comment] 2020-06-23 16:36
Yes, it is saved.

**Comment by rmshaffer** [comment] 2020-06-23 16:39
Can you please run the following Python script to see whether the Python code is correctly finding your Q# operation?

```
import qsharp
qsharp.reload()
print(qsharp.get_available_operations())
```
You should see:
```
['HelloWorld.SayHello']
```

**Comment by zhizeng8** [comment] 2020-06-23 16:42
It returns:
['Qrng.SampleQuantumRandomNumberGenerator', 'Qrng.SampleRandomNumber', 'Qrng.SampleRandomNumberInRange']

**Comment by zhizeng8** [comment] 2020-06-23 16:45
It finally works after I delete the Program.qs file.

**Comment by zhizeng8** [comment] 2020-06-23 16:45
Thank you very much!

**Comment by gillenhaalb** [comment] 2020-06-23 16:47
😆 I was in midst of typing a long potential thought/suggestion, and it's comforting to hear it wasn't that. Happy you got it working!

**Closed by gillenhaalb** 2020-06-23 16:47 UTC
Labels: question

**Comment by rmshaffer** [comment] 2020-06-23 16:49
I see! This is an interesting issue caused by the fact that you have multiple .qs files, and your other .qs file must have contained an `@EntryPoint()` operation, which was causing this operation in the other file to be invisible to Python. I can reproduce this as well. I will open an issue in the https://github.com/microsoft/iqsharp repo for this. Thank you for reporting, and I'm glad you got it working!
