### ISSUE TITLE
symbols and formulas

### ISSUE THREAD

**Issue by sutteri** [MicrosoftDocs/quantum-docs-pr#885] opened 2020-06-04 06:21 UTC
[Enter feedback here]
the whole series of webpage microsoft quantum computing kit webpages have error on webpage...
the math symbols and formula and other stuff involving math..are not appearing properly ..
thank u 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectors and matrices in quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by geduardo** [comment] 2020-06-04 14:59
Thank you @sutteri. We are aware of this issue that appeared recently on our documentation: LaTeX formulas are not rendering correctly. We are working hard to fix it. I'll inform you when the problem is solved.

**Comment by sutteri** [comment] 2020-06-04 17:22
thanks for the response @geduardo !  I hope this gets resolved soon !!

**Comment by geduardo** [comment] 2020-06-08 02:53
Closing since it's a duplicate of #884.

**Closed by geduardo** 2020-06-08 02:53 UTC
Labels: rendering

**Comment by sutteri** [comment] 2020-06-08 06:41
is the webapages fixed ?? how much time ???
