### ISSUE TITLE
Latex

### ISSUE THREAD

**Issue by gonzrubio** [MicrosoftDocs/quantum-docs-pr#895] opened 2020-06-06 21:14 UTC
I am not able to see the equations in any of the concepts. I can see that is there in latex but it doesn't not convert properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4d51b3a-7210-a5c6-135b-c176e6795e0a
* Version Independent ID: 1f2bef66-bc42-45ca-3476-6fea1d5569bf
* Content: [Quantum algorithms in Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/standard/algorithms)
* Content Source: [articles/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/algorithms.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro@microsoft.com**

**Comment by geduardo** [comment] 2020-06-08 02:51
Thank you for opening this issue. The team is already aware of this problem and we are working to solve it ASAP. 

I'll close this issue since it's a duplicate of #884 and #885.

**Closed by geduardo** 2020-06-08 02:51 UTC
