### ISSUE TITLE
[Minor] Quantum Chemistry Doc Fix 

### ISSUE THREAD

**Issue by bettinaheim** [MicrosoftDocs/quantum-docs-pr#490] opened 2019-08-19 21:42 UTC
https://docs.microsoft.com/en-us/quantum/libraries/chemistry/samples/loading-from-file?view=qsharp-preview
Fix the variable in the line “var jordanWignerEncoding = JordanWignerEncoding.Create(generalHamiltonian);”
We should be using the variable “hamiltonian” described above, not “generalHamiltonian” which is not initialized. :)

**Comment by tcNickolas** [comment] 2019-10-06 16:16
This seems to have been fixed in [#436](https://github.com/MicrosoftDocs/quantum-docs-pr/commit/3dfc7845f9dad4c8fb88d0ee7d3d738636d555ad#diff-7d52f46b50c9b46819549a53df7c25e9), though I'm not sure how the timing works - that PR has been merged to live branch in the end of May, while the issue is from August?

**Closed by tcNickolas** 2019-10-06 16:16 UTC
Labels: bug
