### ISSUE TITLE
No clear links to downloadable material

### ISSUE THREAD

**Issue by Biep** [MicrosoftDocs/quantum-docs-pr#907] opened 2020-06-11 09:33 UTC
I want to work off-line, so I am looking for PDF, PS, ePub - whatever, even a simple TXT document would be better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2637b72d-91a2-fb93-11c9-9f73b44a77a1
* Version Independent ID: 11657f10-6c70-cae9-81b8-9c3a58d65d67
* Content: [Q# Basics - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/basics)
* Content Source: [articles/user-guide/basics.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/basics.md)
* Product: **quantum**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec@microsoft.com**

**Comment by gillenhaalb** [comment] 2020-06-11 11:43
Hi @Biep, thanks for raising the point. That's indeed something we have seen the need for, and the struggles to getting PDF download links come primarily from the LaTeX math rendering. 

I personally also enjoy working from our docs offline, and have been making use of a workaround by using the "Print" function of my browser. On Chrome/Windows at least, I am able to select "Print to PDF" as the destination printer, and then save the fully-rendered page as a PDF. I'd imagine this is likely possible on other browsers and operating systems as well. I hope this might be a suitable workaround for the time being.

**Comment by Biep** [comment] 2020-06-11 12:45
True, but the result doesn't show well on an e-reader, and it is a lot of work because the information is spread over many web pages.
LaTeX to PDF can't be *that* hard, can it?

**Comment by geduardo** [comment] 2020-06-11 15:18
Possible duplicate of #776

**Closed** 2020-06-23 18:49 UTC
